source 'https://rubygems.org'

gem 'pry'
gem 'pry-coolline'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
#gem 'stretcher'
gem 'slim'
gem 'cicero'

gem 'aws-sdk'
gem 'elasticsearch'
gem 'faraday_middleware'
gem 'faraday_middleware-aws-signers-v4'
